services:
 db:
  image: mysql
  networks:
    - mynetwork
  ports:
    - "3307:3306"
  environment:
   - MYSQL_PASSWORD=root
   - MYSQL_DATABASE=meupet
   - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
 api:
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/meupet
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: root
  build: .
  image: meupetapi
  networks:
   - mynetwork
  ports:
   - "8080:8080"
  depends_on: 
   - db
   
networks:
 mynetwork:
  driver: bridge
