CREATE TABLE usuario (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 phone_number VARCHAR(20) NOT NULL,
 createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
 updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 moedaCapiba INT DEFAULT 0
);

CREATE TABLE parceiro (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nome_fantasia VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL,
 registro_pessoal VARCHAR(20) NOT NULL,
 senha VARCHAR(255) NOT NULL,
 telefone VARCHAR(20) NOT NULL,
 createdAt DATETIME,
 updatedAt DATETIME
);

